Repository openedx/frontend-app-account, pull requests merged in 2023-10, with the labels that each got.

#891 feat: remove (long-disabled) coaching functionality
  .env
  .env.development
  .env.test
  README.rst
  src/account-settings/AccountSettingsPage.jsx
  src/account-settings/coaching/CoachingConsent.jsx
  src/account-settings/coaching/CoachingConsent.messages.js
  src/account-settings/coaching/CoachingConsentForm.jsx
  src/account-settings/coaching/CoachingToggle.jsx
  src/account-settings/coaching/CoachingToggle.messages.js
  src/account-settings/coaching/data/service.js
  src/account-settings/coaching/test/CoachingConsent.test.jsx
  src/account-settings/coaching/test/__snapshots__/CoachingConsent.test.jsx.snap
  src/account-settings/data/selectors.js
  src/account-settings/data/service.js
  src/i18n/messages/ar.json
  src/i18n/messages/de.json
  src/i18n/messages/de_DE.json
  src/i18n/messages/es_419.json
  src/i18n/messages/fa_IR.json
  src/i18n/messages/fr.json
  src/i18n/messages/fr_CA.json
  src/i18n/messages/hi.json
  src/i18n/messages/it.json
  src/i18n/messages/it_IT.json
  src/i18n/messages/pt.json
  src/i18n/messages/pt_PT.json
  src/i18n/messages/ru.json
  src/i18n/messages/uk.json
  src/i18n/messages/zh_CN.json
  src/index.jsx
  src/index.scss
Labels: engineering-review

#903 fix: Correction to the language code for Português, Italian and German
  src/account-settings/site-language/constants.js
Labels: open-source-contribution

#926 fix: error when trying to save 'other education'
  src/account-settings/AccountSettingsPage.messages.jsx
  src/account-settings/data/constants.js
Labels: open-source-contribution, waiting for eng review, backport

#916 fix: trim long text in links in the social networks block
  src/account-settings/EditableField.jsx
Labels: open-source-contribution

#915 fix: trim long text in links in the social networks block
  src/account-settings/EditableField.jsx
Labels: open-source-contribution, waiting for eng review, backport

#863 feat: add toggling for the hardcode support link
  .env
  .env.development
  .env.test
  src/account-settings/delete-account/BeforeProceedingBanner.jsx
  src/account-settings/delete-account/BeforeProceedingBanner.test.jsx
  src/account-settings/delete-account/DeleteAccount.jsx
  src/account-settings/delete-account/__snapshots__/BeforeProceedingBanner.test.jsx.snap
Labels: open-source-contribution, waiting for eng review, backport

#927 fix: trim long text in links in the social networks block
  src/account-settings/EditableField.jsx
Labels: open-source-contribution
