Repository openedx/frontend-app-account, pull requests merged in 2025-08, with the labels that each got.

#1318 chore: updated the notification section description
  src/notification-preferences/NotificationSettings.jsx
  src/notification-preferences/messages.js
Labels: open-source-contribution

#994 feat: Restore jump nav and content width
  src/account-settings/AccountSettingsPage.jsx
  src/account-settings/JumpNav.jsx
Labels: open-source-contribution

#1298 Replace of injectIntl with useIntl() 3/10
  src/account-settings/EditableField.jsx
  src/account-settings/EmailField.jsx
  src/id-verification/panels/GetNameIdPanel.jsx
  src/id-verification/panels/IdContextPanel.jsx
  src/id-verification/tests/panels/GetNameIdPanel.test.jsx
  src/id-verification/tests/panels/IdContextPanel.test.jsx
Labels: open-source-contribution, mao-onboarding

#1305 Replace of injectIntl with useIntl() 7/10
  src/account-settings/DOBForm.jsx
  src/account-settings/EditableSelectField.jsx
  src/account-settings/JumpNav.jsx
  src/account-settings/test/EditableSelectField.test.jsx
  src/account-settings/test/JumpNav.test.jsx
Labels: open-source-contribution, mao-onboarding

#1306 Replace of injectIntl with useIntl() 8/10
  src/id-verification/panels/EnableCameraDirectionsPanel.jsx
  src/id-verification/panels/PortraitPhotoContextPanel.jsx
  src/id-verification/panels/RequestCameraAccessPanel.jsx
  src/id-verification/tests/panels/PortraitPhotoContextPanel.test.jsx
  src/id-verification/tests/panels/RequestCameraAccessPanel.test.jsx
Labels: open-source-contribution, mao-onboarding

#1024 fix: long email field on account page
  src/account-settings/EmailField.jsx
  src/account-settings/_style.scss
Labels: open-source-contribution, create-sandbox
